### ISSUE TITLE
Don't add undocumented fields to appstore.Receipt struct

### ISSUE THREAD

**Issue by zjx20** [dogenzaka/go-iap#28]
Some fields of `appstore.Receipt` are not mentioned in the [Apple IAP Doc](https://developer.apple.com/library/ios/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW3), such as `ReceiptType`, `AdamID` and `AppItemID`. Although they are appear in the response, using them can be a risk. Because they are not promised by Apple, things would be changed in the future.

So that I suggest that they should be removed to avoid misuse.

**Comment by jun06t** [comment]
Thanks for your suggestion.

Apple's document really annoys me, because some fields are mentioned as incorrect type.
__ex)__ ``expires_date`` says _number_ in the document but response shows _string_ like _"2015-07-09 08:24:17 Etc/GMT"_
And some fields are worth using such as ``xxx_date_ms``, although they are not mentioned.

So I'll leave this ``IAPResponse`` struct and make the ``Verify()`` function use _interface{}_ argument so that you can use the response struct you defined.
